#!/bin/sh

while true
do
	echo "Please enter commands:"
	read cmd arg
	if ("$cmd" ==  "echo")
	then
	    echo "${arg}"
	elif ("$cmd" ==  "cat")
	then
	    cat ${arg}
	elif ("$cmd" ==  "ls")
	then
	    ls ${arg}
	elif ("$cmd" ==  "exit")
	then
	    echo "Thank you!"
	    exit 1
	else
	    echo "No Command Found!"
	 fi
done





